# Generated by Django 4.0.3 on 2022-04-06 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['rating']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['create_date']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['count']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['nickname']},
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.question'),
        ),
        migrations.AddField(
            model_name='tag',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
